[2024-02-16T00:25:49.907+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: spotify_to_rds_dag.extract_data_task scheduled__2024-02-15T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
