[2024-02-15T15:02:19.582+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: spotify_to_rds_dag.extract_data_task manual__2024-02-15T15:02:17.295658+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
